language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            # safelist
branches:  
only:  
- master  
- stable  
# blocklist
branches:  
except:  
- legacy  
- experimental
script:
- mkdir build
- cd build
- cmake .. && make
